export type WorkbenchLocale = "zh-CN" | "en-US";

/** Central default UI copy; stable keys survive component moves. */
const zhCopy = {
  observationStatus: "观察状态",
  observationStale: "观察数据可能已过期",
  observationUnavailable: "观察暂不可用",
  refreshNow: "立即刷新",
  observationRefreshing: "正在刷新",
  observationDegraded: "刷新暂时失败",
  observationAreaList: "工作区列表",
  observationAreaDetail: "仓库详情",
  observationAreaGraph: "提交图",
  observationAreaChanges: "变化列表",
  statusWorkspaceList: "工作区列表",
  statusRepositories: "仓库状态",
  statusGraph: "提交图",
  statusChanges: "变化列表",
  openFailed: "面板未能打开，请从全局入口重试",
  projectLoading: "正在读取项目配置…",
  hostWorkspaceLoading: "正在读取当前工作区…",
  hostWorkspaceUnavailable: "当前工作区暂不可用",
  projectLoadFailed: "项目配置暂不可用",
  selectProject: "选择项目",
  switchProject: "切换项目",
  noRegisteredProjects: "尚未登记项目配置，请先安装项目服务",
  setupTitle: "开始使用 Workbench",
  setupDescription: "选择要观察的 Git 仓库。",
  setupScanning: "正在检查项目…",
  setupScanFailed: "无法读取项目",
  setupNoGit: "当前目录中没有可用的 Git 仓库",
  setupGitHint: "请安装 Git，或打开一个 Git 项目。",
  setupProjectRoot: "项目目录",
  setupRepositories: "仓库",
  setupParentRepository: "父仓库（默认）",
  setupNestedRepositories: "可选子仓库",
  setupNestedHint: "按需添加",
  setupNoNested: "没有发现可选子仓库",
  setupStorage: "配置存储",
  setupSideEffect: "不会创建分支或 worktree",
  setupAdvanced: "高级设置",
  setupShareConfig: "共享配置",
  setupShareHint: "允许提交配置；运行数据仍在本机。",
  setupLocalOnly: "仅本机",
  setupSave: "保存并开始",
  setupSaveFailed: "保存项目配置失败",
  setupSaving: "正在保存并启动…",
  setupBackendStarting: "正在启动 Workbench…",
  setupBackendTitle: "Workbench 服务",
  setupBackendFailed: "配置已保存，但 Workbench 服务尚未就绪。",
  setupBackendMissing: "配置已保存，但找不到 Workbench 服务。",
  setupBackendRetryHint: "项目扫描结果仍然保留；准备好后可以重试启动。",
  setupRetry: "重试",
  storageMenu: "项目存储位置",
  storageConfig: "配置",
  storageWorktrees: "隔离目录",
  storageState: "运行状态",
  storageSocket: "服务 Socket",
  storageGitLocal: "本机忽略",
  storageGitShared: "配置可提交",
  storageGitIgnored: "已被 Git 忽略",
  storageGitExternal: "项目外存储",
  storageGitUnavailable: "项目 Git 不可用",
  storageLoading: "正在读取存储位置…",
  storageUnavailable: "存储位置暂不可用",
  runtimeSettingsMenu: "项目运行时设置",
  runtimeSettingsTitle: "项目运行时与缓存",
  runtimeSettingsMode: "运行时策略",
  runtimeSettingsAuto: "自动（优先系统）",
  runtimeSettingsSystem: "仅系统运行时",
  runtimeSettingsMise: "仅 mise",
  runtimeSettingsModeHint: "自动模式找不到匹配版本时才会使用 mise。",
  runtimeSettingsManagerPath: "mise 路径（可选）",
  runtimeSettingsRuntimePaths: "运行时搜索路径（每行一个，可选）",
  runtimeSettingsRuntimePathsHint: "用于图形界面启动时 PATH 不完整的环境。",
  runtimeSettingsCache: "项目共享缓存",
  runtimeSettingsCacheEnabled: "启用项目级缓存",
  runtimeSettingsCacheRoot: "缓存目录（可选）",
  runtimeSettingsRequirements: "运行时要求（JSON）",
  runtimeSettingsRequirementsHint: "按仓库填写，例如 {\"halh\":{\"go\":\"1.26\"}}。",
  runtimeSettingsLoading: "正在读取运行时设置…",
  runtimeSettingsReadFailed: "运行时设置暂不可用",
  runtimeSettingsInvalidRequirements: "运行时要求必须是 JSON 对象，并为每个工具填写版本。",
  runtimeSettingsSave: "保存并应用",
  runtimeSettingsSaving: "正在应用…",
  runtimeSettingsSaveFailed: "运行时设置保存失败",
  setupDirty: "有未提交变更",
  setupClean: "工作区干净",
  setupDetached: "分离 HEAD",
  setupNoCommits: "尚无提交",
  setupInvalidRepository: "不是有效的 Git 仓库",
  historyScroll: "已显示 {0} 条 · 向下滚动继续加载",
  "productName": "Workspace Workbench",
  "changesTitle": "Workspace Changes",
  "openWorkbench": "打开 Workspace Workbench",
  "headerLabel": "Workbench",
  "readOnlyObservation": "只读观察",
  "toolchainLabel": "工具链 · ",
  "text_fb36ad230f": "Observer 请求失败",
  "text_f7e720248d": "可快进",
  "text_ee5b0077ae": "已包含",
  "text_da56864458": "已分叉",
  "text_27b5842c97": "待确认",
  "text_c7ae08f54c": "选择一个 Workspace",
  "text_4f91d2c9ad": "只读 · 当前源目录",
  "text_f496a15d9d": "观察暂时未完成，正在重试。",
  "text_b30f770e31": "观察暂时未完成，请稍后重试。",
  "text_b71f1b83e5": "首次观察尚未完成，请稍后重试。",
  "text_bb57803d41": "主工作区只支持观察，不能交接 Agent",
  "text_d7dd46e5e3": "请从主控 Agent 面板发起交接",
  "text_afa9beb681": "请先填写本次交接目标",
  "text_36cdf2a07a": "继续执行上一次 handoff：先完成只读 preflight；若仍存在偏差则停止并报告。",
  "text_a2eb60ef6c": "已创建执行 Agent",
  "text_0561f1d18e": "执行 Agent 已在运行",
  "text_050246dd54": "已恢复执行 Agent",
  "text_962c002fa2": "交接已提交",
  "text_b4f57a0af8": "交接未完成",
  "text_341baadc12": "交接请求失败",
  "text_2fb0b81c28": "已复制合并说明",
  "text_514f0cbbf2": "复制失败，请选择文本复制",
  "text_1623afda9e": "新建 Workspace",
  "text_76848596cb": "Workspace 名称",
  "text_deb3990191": "创建失败",
  "text_1680b04bf6": "创建中…",
  "text_fcbd093292": "创建",
  "text_1b37d56f7a": "交接目标",
  "text_99ad8551f2": "交接",
  "text_ddb6624fda": "Observer 暂不可用",
  "text_d019a92a84": "刷新观察",
  "text_0334dc4b93": "数据可能已过期 · ",
  "text_a6625c543c": "上次观察 · ",
  "text_15c5640f77": "等待启动",
  "text_fb0309dda4": "初始化中",
  "text_1f425b6bf0": "执行中",
  "text_837e7a109a": "空闲",
  "text_4c5958e011": "等待权限",
  "text_e99b48a29b": "已完成",
  "text_059c4d4016": "已阻塞",
  "text_9746cfc7d2": "执行失败",
  "text_f628761bf5": "已关闭",
  "text_5cfbea2b76": "已归档",
  "text_87f8d08d81": "尚未交接",
  "text_b21b631cd5": "读取中",
  "text_95abdc4ebd": "状态未知",
  "text_5ce2e6f402": "Agent",
  "text_f7acefd2d4": "查看",
  "text_2b6021df2f": "重试交接",
  "text_6cea90adcf": "Workspace Workbench",
  "text_ca42ecd50e": "观察 · Agent 状态",
  "text_1744b62533": "打开 Observer 布局菜单",
  "text_88b31c6b96": "Observer 布局",
  "text_07333899fd": "调整三个观察区域的显示方式",
  "text_5f6a1bf190": "全部折叠",
  "text_66c98ab6d8": "全部展开",
  "text_e003f209ca": "恢复默认布局",
  "text_4d0b4688c7": "取消",
  "text_21eaf73725": "正在刷新",
  "text_778fc8f994": "全部",
  "text_284b34e15f": "需关注",
  "text_05162ec10a": "未推送",
  "text_be78b20585": "历史",
  "text_80bf719ff7": "正在观察…",
  "text_205b4561ed": "Workspaces",
  "text_42099b4af0": "/",
  "text_daa32fe25c": "没有匹配的 Workspace。",
  "text_96c3e67563": "正在读取 Workspace…",
  "text_07f7471155": "当前暂时没有可展示的 Workspace 数据。",
  "text_981b8eb33f": "选择 Workspace 开始观察。",
  "text_6bb9866496": "当前 Workspace 没有可读取的子仓。",
  "text_9fd34d1b5f": "需要准备",
  "text_5395180221": "部分完成",
  "text_273309c58d": "准备失败",
  "text_005b60faae": "缺少 mise",
  "text_81772f8606": "缺少系统命令",
  "text_a94df0c5c2": "版本冲突",
  "text_9e44dbbc0e": "请准备此仓库的运行时。",
  toolchainPrepare: "准备运行时",
  toolchainPreparing: "正在准备运行时…",
  "text_f52ac96bcc": "MISE 工具链 ·",
  "text_ededcbb377": "repos",
  "text_f9f75e6112": "暂未更新",
  "text_97def2ca9e": " · HEAD ",
  "text_80a8716fca": "完整历史",
  "text_ddde5db955": "未配置上游",
  "text_62b4069970": "返回当前范围",
  "text_a86af73bae": "收起详情",
  "text_4f55ee1e68": "详情",
  "text_1405df66cb": "base ",
  "text_fcabadb2a7": "正在读取…",
  "text_a07cd6a10e": "没有可展示的提交。",
  "text_76c6f5f575": "正在加载历史…",
  "text_f9d6d6a329": "已达到单次历史上限",
  "text_5731f87e8f": "已到达历史起点",
  "text_c9b020caa5": " · 已显示 ",
  "text_ef7c82a2b7": "WORKTREE",
  "text_41e5243e2d": "目录",
  "text_49deaf7da2": "文件",
  "text_95c0f75473": "变化列表暂未完成刷新 · 保留上次观察",
  "text_5ee36e41d4": "当前范围没有文件变化。",
  "text_5200400653": "选择工作区",
  "text_91a9479226": "commits ·",
  "text_9de8dab0bd": "重复 ·",
  "text_be8ffa22c8": "合并说明",
  "text_55f59bc2f0": "复制全部",
  "text_5d5815647c": "收起",
  "text_b0e24833f7": "展开",
  "text_5e509c6853": "选择 Workspace 开始分析。",
  "text_a7fc5b37a4": "文件变化暂时不可用，请稍后重试。",
  "text_c580606e1c": "未提交",
  "text_09cbc97ae2": "提交",
  "text_d1d2ccdd33": "分支提交",
  "text_eb8343b3df": "WORKSPACE / REVIEW WORKBENCH",
  "text_01970ba582": "Workspace Changes",
  "text_45300063e6": "只读文件审查 · ",
  "text_6298371965": "选择一个变更文件",
  "switchToUnified": "切换为统一审查",
  "switchToSplit": "切换为并排审查",
  "readOnlyBadge": "只读文件审查",
  "text_9af2506454": "READ ONLY",
  "text_336884b48e": "从 Workspace Workbench 选择文件后，会在这里打开审查标签。",
  "text_e80b21bb56": " · head ",
  "text_6d6e071a12": "暂时未更新 · 保留上次 Diff",
  "text_a74b5d91fa": "正在读取文件变化…",
  "text_982b60ebcc": "选择一个文件开始审查",
  "text_5720774925": "Workbench 中的 Changed tree 会把文件打开到这个主区标签；原来的 Agent 会话仍然保留。",
  "text_a1a0e61a02": "二进制文件",
  "text_8476fa5fe9": "这个文件没有可读的文本 Diff。",
  "text_fd707df26d": "没有可显示的文本变化",
  "text_81f977c1ab": "可能是空文件、文件已缺失，或 Git 没有返回 patch。",
  "text_1d3d755616": "Diff 内容已按 Observer 限制截断。",
  "text_dd4a011844": "+ added",
  "text_e103af637d": "~ modified",
  "text_2e359e4f5a": "− removed",
  "text_0d310558b7": "上一个变化区块",
  "text_d8b1574142": "下一个变化区块",
  "text_db427e2fe9": "工作树不存在",
  "text_e0ea8945c4": "Workspace 记录无效",
  "text_ec1e4a1e10": "文件路径无效",
  "text_8c9ee7d66a": "文件已不在当前变更范围",
  "text_e7404b46f4": "提交已不可用",
  "text_f3ec0129e4": "缺少基准提交",
  "text_2f51f7e68d": "仓库不属于当前 Workspace",
  "text_caa94a3fdf": "仓库处于 detached 状态",
  "text_6b9afea9f1": "需要查看详情",
  "text_6dbf7070d6": "未观察",
  "text_9e636642d6": "刚刚",
  "text_adea7d427f": "刚刚观察",
  "text_fcd9714424": "无活动时间",
  "text_6478dde454": "时间未知",
  "text_3f2e139043": "Paseo 设置读取失败",
  "text_c075ee72ab": "Paseo 设置格式无效",
  "text_abffafb4f9": "Workspace Workbench 查询超时，已保留上次观察结果。",
  "text_64c3cc39e8": "Workspace Workbench 服务未启动，请先启动服务。",
  "text_83008521f9": "Workspace Workbench 服务暂时不可用。",
  "text_61af484c81": "{0} 分钟前观察",
  "text_607909447d": "{0} 分钟前",
  "text_87a6439b2e": "{0} 小时前",
  "text_9094e27946": "{0} 天前",
  "text_f41a05dfe8": "Agent 接管状态：{0}",
  "text_b5d0217a47": "所选提交",
  "text_b6a933155a": "未提交变化",
  "text_f30d1e7faf": "分支变化",
  "text_eac4c5d4a1": "提交图",
  "text_22c7a14625": "未提交 {0}",
  "text_46b798f402": "分支变化 {0}",
  "text_f69ff23be4": "加载更多提交 · 已显示 {0}",
  "text_29e918bbdd": "  未提交 · {0}",
  "text_2e046dd497": "{0} 个 workspace",
  "text_c91e6e6a53": "仓库",
  "text_8fae4f2a02": "无变化",
  "text_e50d9d028a": "目标分支",
  "text_a5b4c3b08d": "请选择目标分支",
  "text_39e5b16a6b": "调整 {0} 区域高度",
  diffOverview: "Diff 概览",
  diffHunk: "Diff 区块 {0}",
  reviewTargetBranch: "目标分支",
  agentCoordinatorRequired: "请从主控会话交接",
  workspacePreviewRequired: "请先完成只读 Workspace 预览；执行必须使用相同的请求身份。",
  agentModeUnconfirmed: "无法确认执行模式或权限，请在主控会话检查后重试",
  agentBusyOtherTask: "Agent 正在处理其他交接任务",
  agentClosedRecovery: "已有 Agent 已关闭，需要显式恢复，未创建重复 Agent",
  createSearch: "搜索仓库",
  createBase: "设置起点（默认源码 HEAD）",
  createMissing: "源码不可用",
  createCatalogFailed: "仓库列表暂不可用，请重新打开重试",
  createResize: "调整 Workspace 创建窗口内容高度",
  agentContextUnavailable: "当前会话未接入 Workbench 工具，请新建主控会话",
  agentContextLoading: "正在确认 Workbench 工具状态…",
  agentContextReady: "Workbench 工具已接入",
  workspaceStatusDirty: "有变更",
  workspaceStatusUnpushed: "未推送",
  workspaceStatusNeedsReview: "需关注",
  workspaceStateRemoved: "已移除",
  workspaceStateDeletionPending: "待删除",
  workspaceStateCreateFailed: "创建失败",
  workspaceCreateFailedTitle: "Workspace 创建失败",
  workspaceCreateFailedDescription: "创建过程没有完成，因此没有可观测的 Git worktree 或提交图。",
  workspaceCreateFailedRecovery: "请先准备工具链，或移除这条失败记录后重新创建。",
  workspaceDelete: "移除 Workspace",
  workspaceRestore: "恢复 Workspace",
  workspacePermanentDelete: "永久删除",
  workspaceDeleteImpact: "查看删除影响",
  workspaceDeleteTitle: "删除 Workspace",
  workspaceDeleteDescription: "普通移除只隐藏 Workspace，并保留分支、提交、未提交修改和任务记录。",
  workspaceDeleteRunningTask: "运行中的任务",
  workspaceDeleteDirty: "未提交修改",
  workspaceDeleteUnpushed: "未推送提交",
  workspaceDeleteExternal: "外部引用",
  workspaceDeletePreserve: "将保留",
  workspaceDeleteLose: "永久删除将移除",
  workspaceDeleteConfirm: "确认永久删除",
  workspaceDeleteCancel: "取消",
  workspaceDeleteQueued: "任务运行中，已进入待删除；新任务已阻止。",
  workspaceDeleteReady: "任务已结束，可以完成移除。",
  workspaceDeleteSuccess: "Workspace 已移除，可从历史恢复。",
  workspaceRestoreSuccess: "Workspace 已恢复。",
  workspacePermanentDeleteSuccess: "Workspace 已永久删除；分支和外部引用保留。",
  workspaceDeleteFailed: "Workspace 删除操作失败",
  workspaceDeleteStopTask: "请先停止或完成运行中的任务",
  workspaceDeleteTaskStillRunning: "任务仍在运行，暂不能永久删除",
  workspaceDeletePermanentWarning: "此操作不可撤销，会移除托管 worktree 和未提交文件；分支不会被删除。",
  workspaceDeleteRuntimeState: "运行时记录",
  workspaceDeleteRuntimeImpact: "永久删除会清理当前 Workspace 的 Agent 绑定和 Review 记录，但不会删除外部 Agent 本体。",
  workspaceDeleteRuntimeBinding: "Agent 绑定",
  workspaceDeleteRuntimeReview: "{0} 条 Review 记录",
  workspaceDeleteUnavailable: "删除影响暂不可用，请刷新后重试。",
  workspaceDeleteBranchPreserved: "分支、提交和外部引用不会因逻辑移除而删除。",
  tabWorkspace: "工作区",
  tabReviewSet: "审核集",
  tabAgentReview: "Agent 审核",
  reviewTitle: "Agent 审核",
  reviewNoFlow: "当前工作区还没有审核流程。",
  reviewLoading: "正在读取审核流程…",
  reviewStatusWaitingExecution: "等待执行",
  reviewResumeWaitingReport: "审核流程已恢复，等待执行会话提交新的完成报告。任务不会自动重发；执行结束后也可点击“开始审核”。",
  reviewStatusReady: "待审核",
  reviewStatusQueued: "排队中",
  reviewStatusReviewing: "审核中",
  reviewStatusChanges: "需要修改",
  reviewStatusFixing: "修复中",
  reviewStatusApproved: "已通过",
  reviewStatusBlocked: "已阻塞",
  reviewStatusFailed: "失败",
  reviewStatusStopping: "正在停止",
  reviewStatusStopped: "已停止",
  reviewStatusLimit: "达到上限",
  reviewRound: "第 {0} / {1} 轮",
  reviewRoundShort: "第 {0} 轮",
  reviewHistory: "历史流程：{0} 个",
  reviewExecutionAgent: "执行 Agent",
  reviewReviewer: "Reviewer",
  reviewRepair: "执行 Agent 修复",
  reviewEventStarted: "审核流程已开始",
  reviewEventExecutionTurnEnded: "执行回合已结束",
  reviewEventReady: "执行 Agent 已提交审核",
  reviewEventQueued: "审核已排队",
  reviewEventReviewerCreated: "只读 Reviewer 已创建",
  reviewEventReviewStarted: "审核已开始",
  reviewEventCandidate: "已收到审核候选结果",
  reviewEventResult: "审核结果",
  reviewEventRepairRequested: "已请求执行 Agent 修复",
  reviewEventRepairSent: "修复任务已发送",
  reviewEventPaused: "审核已暂停",
  reviewEventResumed: "审核已恢复",
  reviewEventStopped: "审核已停止",
  reviewEventFailed: "审核失败",
  reviewEventBlocked: "审核被阻塞",
  reviewEventExpired: "审核版本已过期",
  reviewEventFinished: "审核流程已结束",
  reviewRoleExecution: "执行 Agent",
  reviewRoleReviewer: "Reviewer",
  reviewRoleRepair: "执行 Agent 修复",
  reviewCompleted: "已完成",
  reviewExpand: "展开完整内容",
  reviewCollapse: "收起完整内容",
  reviewLatestResult: "最新审核结果",
  reviewFindingCount: "发现 {0} 项问题",
  reviewNoFindings: "没有必须修改的问题",
  reviewCheckPassed: "通过",
  reviewCheckFailed: "失败",
  reviewCheckNotRun: "未执行",
  reviewCheckUnavailable: "不可用",
  reviewSeverityInfo: "建议",
  reviewSeverityWarning: "警告",
  reviewSeverityError: "错误",
  reviewViewDiff: "查看差异",
  reviewViewExecution: "查看执行会话",
  reviewViewReviewer: "查看审核会话",
  reviewViewConversation: "查看完整对话",
  reviewChanges: "变更",
  reviewTests: "测试",
  reviewKnownLimitations: "已知限制",
  reviewStart: "开始审核",
  reviewContinue: "继续审核",
  reviewRepairAction: "继续修复",
  reviewStop: "停止",
  reviewResume: "恢复流程",
  reviewStartNew: "开始新的审核",
  reviewSettingsMenu: "审核配置",
  reviewSettingsTitle: "审核配置",
  agentSessionSettings: "Agent 会话设置",
  reviewSettingsScopeProject: "本项目",
  reviewSettingsScopeGlobal: "全局默认",
  reviewSettingsInheritedHint: "未单独设置的字段继承全局默认。",
  agentSessionPermissionSettings: "新建执行 Agent 的权限",
  agentSessionPermissionHint: "仅影响之后新建的执行 Agent；已有 Agent 不变。",
  agentSessionPermissionInherit: "跟随当前 Agent",
  agentSessionPermissionAuto: "自动",
  agentSessionPermissionAutoReview: "自动审核",
  agentSessionPermissionFullAccess: "完整访问",
  reviewSettingsIndependent: "独立会话",
  reviewSettingsIndependentShort: "独立",
  reviewSettingsChildAgent: "子 Agent",
  reviewSettingsFollowDefault: "跟随默认",
  reviewSettingsProviderOverrides: "Provider 覆盖",
  reviewSettingsMode: "审核模式",
  reviewSettingsModeOff: "关闭",
  reviewSettingsModeManual: "手动",
  reviewSettingsModeAutomatic: "自动",
  reviewSettingsAutoFix: "自动修复",
  reviewSettingsManualFix: "手动修复",
  reviewSettingsRole: "Reviewer 角色",
  reviewSettingsInstructions: "审核要求",
  reviewSettingsMaxRounds: "最大审核轮次",
  reviewSettingsTimeout: "超时",
  reviewSettingsReviewerTimeout: "审核",
  reviewSettingsRepairTimeout: "修复",
  reviewSettingsReviewerTimeoutPlaceholder: "审核分钟",
  reviewSettingsRepairTimeoutPlaceholder: "修复分钟",
  reviewSettingsChecks: "检查",
  reviewSettingsReviewerSession: "Reviewer 会话",
  reviewCoordinator: "主控审核",
  handoffMaterials: "交接资料",
  handoffMaterialsUnavailable: "交接资料暂时不可读取",
  handoffConversation: "会话归档",
  handoffRequired: "必读资料",
  handoffFetched: "已获取（不代表已理解）",
  handoffNextPage: "下一段",
  reviewCoordinatorWaiting: "等待主控空闲",
  reviewCoordinatorUncertain: "审核投递待确认",
  reviewCoordinatorSent: "等待主控接收审核",
  reviewIndependentSwitch: "改用独立 Reviewer",
  reviewCoordinatorOpen: "查看主控会话",
  reviewSettingsReuse: "复用会话",
  reviewSettingsNewPerRound: "每轮新建",
  reviewSettingsExecutionModel: "执行模型",
  reviewSettingsReviewerModel: "Reviewer 模型",
  reviewSettingsFollowExecution: "跟随执行会话",
  reviewSettingsResetExecution: "恢复执行模型继承",
  reviewSettingsResetReviewer: "恢复 Reviewer 模型继承",
  reviewSettingsResetAll: "恢复本项目全部继承",
  reviewSettingsSave: "保存设置",
  reviewSettingsSaved: "审核设置已保存",
  reviewSettingsSaveFailed: "审核设置保存失败",
  reviewSourceProject: "本项目",
  reviewSourceGlobal: "全局",
  reviewSourceDefault: "默认/跟随",
  reviewSourceDefaultShort: "默认",
  reviewDefaultRole: "代码审核者",
  reviewDefaultInstructions: "检查需求是否满足、实现是否正确、是否引入回归、测试是否充分；保持实现简单。",
  reviewPromptIntro: "审核会话 {0}，第 {1} 轮。",
  reviewPromptRead: "服务端会验证读取和结果提交。请先读取固定快照再作出结论。",
  reviewPromptIdentity: "预期快照标识：{0}；预期差异标识：{1}。",
  reviewPromptOriginal: "原始任务上下文：{0}。",
  reviewPromptPrevious: "上一轮审核结果和修复证据：{0}。",
  reviewPromptReturn: "请返回稳定的 finding ID；只有不存在必须修复的问题时才标记为已通过。",
  reviewPromptLanguage: "请使用中文返回审核摘要、问题、建议和检查结果。",
  reviewSystemRole: "你是 {0}。",
  reviewSystemReadOnly: "你只能进行只读审核。请使用专用审核工具读取固定快照并提交结构化结果。",
  reviewSystemNeverWrite: "不要编辑业务文件、运行会修改文件的命令、委派或创建其他 Agent，也不要合并。",
  handoffPacket: "交接资料",
  handoffPreview: "预览交接",
  handoffPreviewTitle: "确认 Agent 交接",
  handoffPreviewHint: "确认后，这份需求资料会被冻结，并同时提供给执行 Agent 和 Reviewer。",
  handoffConfirm: "确认交接",
  handoffEdit: "返回修改",
  handoffDone: "完成编辑",
  handoffUnderstanding: "需求理解",
  handoffUnderstandingPlaceholder: "用自己的话说明要解决什么问题、面向谁、结果是什么。",
  handoffPlan: "计划（每行一项）",
  handoffPlanPlaceholder: "例如：调整设置页；补充空状态；增加测试。",
  handoffAcceptance: "验收标准（每行一项）",
  handoffAcceptancePlaceholder: "例如：未配置时显示空状态；点击保存后提示成功。",
  handoffReferences: "参考文件/图片（每行一个）",
  handoffReferencesPlaceholder: "路径可写 repo:path；主控注册的图片可写 asset:资产ID。",
  handoffAvailableAssets: "可用图片资产（点击加入）",
  handoffReviewInstructions: "本次审核要求",
  handoffReviewInstructionsPlaceholder: "例如：必须对照草稿图检查布局、状态和交互。",
  handoffPacketHint: "这些内容会随本次任务冻结并交给执行 Agent 与 Reviewer。",
  handoffNoPacket: "未填写额外交接资料。",
  handoffReferenceCount: "参考资料 {0} 项",
  handoffAcceptanceCount: "验收标准 {0} 项",
  reviewErrorGeneric: "审核流程暂时不可用",
  reviewErrorExecutionRequired: "请先完成执行 Agent 的任务并提交审核报告。",
  reviewErrorExecutionBusy: "执行 Agent 仍在运行，请稍后再开始审核。",
  reviewErrorModelUnavailable: "配置的 Reviewer 模型不可用。",
  reviewErrorReviewerUnavailable: "Reviewer 会话无法启动。",
  reviewErrorSnapshotStale: "审核期间代码发生变化，请重新审核。",
  reviewErrorReadonlyUnavailable: "当前环境无法确认 Reviewer 的只读权限。",
  reviewErrorDisabled: "审核功能已关闭。",
  reviewErrorExecutionRequiredShort: "请先完成执行 Agent 的任务。",
  reviewErrorExecutionUnavailable: "执行 Agent 当前不可用。",
  reviewErrorExecutionIdentity: "执行 Agent 与当前工作区不匹配。",
  reviewErrorReviewNotReady: "当前还没有可审核的执行结果。",
  reviewErrorSessionNotFound: "找不到审核流程。",
  reviewErrorStateConflict: "审核状态已变化，请刷新后重试。",
  reviewErrorReviewNotActive: "审核流程已结束，不能继续处理。",
  reviewErrorReviewerBusy: "Reviewer 仍在处理上一轮审核。",
  reviewErrorReviewerTimeout: "Reviewer 审核超时。",
  reviewErrorReviewerInvalidResult: "Reviewer 返回的审核结果格式无效。",
  reviewErrorCancelUnavailable: "当前环境无法确认停止结果。",
  reviewErrorPermission: "Reviewer 正在等待权限处理。",
  reviewErrorCodeLabel: "错误代码",
  reviewFindingNeedsFix: "需要修改",
  reviewFindingSuggestion: "建议",
  reviewUnreviewed: "未覆盖",
  reviewCheckEvidence: "证据",
  graphCommitChanges: "提交变化",
  graphHeadWorktree: "HEAD → 工作树",
  graphBaseHead: "基准 → HEAD",
  graphBaseLabel: "基准",
  commitDetails: "提交详情",
  commitAuthor: "作者",
  commitTime: "提交时间",
  commitReferences: "分支/标签",
  commitParentCount: "父提交 {0} 个",
  commitMerge: "合并提交",
  commitBase: "基准提交",
  commitTimeUnknown: "暂无时间信息",
  commitAuthorUnknown: "未知作者",
  commitNoReferences: "无分支或标签",
  graphDetached: "未关联上游",
  branchMissing: "缺少工作树",
  branchDetached: "分离 HEAD",
  fileCountLabel: "{0} 个文件",
  repoCountLabel: "{0} 个仓库",
  gitLabel: "Git",
  localStorageLabel: "本机 · {0}",
  externalStorageLabel: "项目外 · {0}",
  languageFollowSystem: "跟随 Paseo/系统",
  languageChinese: "中文",
  languageEnglish: "English",
} as const;

// Keep the key set inferred from the source language while widening values so
// other locales can provide their own strings instead of being forced to use
// the literal Chinese values from `zhCopy`.
export type WorkbenchCopy = {
  [Key in keyof typeof zhCopy]: string;
};

const enCopy: WorkbenchCopy = {
  ...zhCopy,
  observationStatus: "Observation status",
  observationStale: "Observation may be stale",
  observationUnavailable: "Observation unavailable",
  refreshNow: "Refresh now",
  observationRefreshing: "Refreshing",
  observationDegraded: "Refresh temporarily failed",
  observationAreaList: "Workspace list",
  observationAreaDetail: "Repository details",
  observationAreaGraph: "Commit graph",
  observationAreaChanges: "Changed files",
  statusWorkspaceList: "Workspace list",
  statusRepositories: "Repository status",
  statusGraph: "Commit graph",
  statusChanges: "Changed files",
  openFailed: "The panel could not open. Try it again from the global entry.",
  projectLoading: "Loading project configuration…",
  hostWorkspaceLoading: "Loading current workspace…",
  hostWorkspaceUnavailable: "Current workspace unavailable",
  projectLoadFailed: "Project configuration unavailable",
  selectProject: "Select project",
  switchProject: "Switch project",
  noRegisteredProjects: "No project configuration is registered. Set up the project first.",
  setupTitle: "Set up Workbench",
  setupDescription: "Choose the Git repositories to observe.",
  setupScanning: "Checking project…",
  setupScanFailed: "Unable to read project",
  setupNoGit: "No usable Git repository was found in this directory",
  setupGitHint: "Install Git or open a Git project.",
  setupProjectRoot: "Project directory",
  setupRepositories: "Repositories",
  setupParentRepository: "Parent repository (default)",
  setupNestedRepositories: "Optional nested repositories",
  setupNestedHint: "Add when needed",
  setupNoNested: "No optional nested repositories found",
  setupStorage: "Configuration storage",
  setupSideEffect: "No branch or worktree will be created",
  setupAdvanced: "Advanced settings",
  setupShareConfig: "Share configuration",
  setupShareHint: "Allow the configuration to be committed; runtime data stays local.",
  setupLocalOnly: "Local only",
  setupSave: "Save and start",
  setupSaveFailed: "Failed to save project configuration",
  setupSaving: "Saving and starting…",
  setupBackendStarting: "Starting Workbench…",
  setupBackendTitle: "Workbench service",
  setupBackendFailed: "Configuration saved, but the Workbench service is not ready.",
  setupBackendMissing: "Configuration saved, but the Workbench service was not found.",
  setupBackendRetryHint: "The scan result is retained. Retry when the service is ready.",
  setupRetry: "Retry",
  storageMenu: "Project storage",
  storageConfig: "Configuration",
  storageWorktrees: "Worktree directory",
  storageState: "Runtime state",
  storageSocket: "Service socket",
  storageGitLocal: "Ignored locally",
  storageGitShared: "Configuration committable",
  storageGitIgnored: "Ignored by Git",
  storageGitExternal: "External project storage",
  storageGitUnavailable: "Project Git unavailable",
  storageLoading: "Loading storage location…",
  storageUnavailable: "Storage location unavailable",
  runtimeSettingsMenu: "Project runtime settings",
  runtimeSettingsTitle: "Project runtimes and caches",
  runtimeSettingsMode: "Runtime strategy",
  runtimeSettingsAuto: "Auto (system first)",
  runtimeSettingsSystem: "System runtimes only",
  runtimeSettingsMise: "mise only",
  runtimeSettingsModeHint: "Auto mode uses mise only when a matching system runtime is unavailable.",
  runtimeSettingsManagerPath: "mise path (optional)",
  runtimeSettingsRuntimePaths: "Runtime search paths (one per line)",
  runtimeSettingsRuntimePathsHint: "Useful when a GUI-launched process has a minimal PATH.",
  runtimeSettingsCache: "Project shared caches",
  runtimeSettingsCacheEnabled: "Enable project caches",
  runtimeSettingsCacheRoot: "Cache directory (optional)",
  runtimeSettingsRequirements: "Runtime requirements (JSON)",
  runtimeSettingsRequirementsHint: "For example: {\"halh\":{\"go\":\"1.26\"}}.",
  runtimeSettingsLoading: "Reading runtime settings…",
  runtimeSettingsReadFailed: "Runtime settings are unavailable",
  runtimeSettingsInvalidRequirements: "Runtime requirements must be a JSON object with a version for each tool.",
  runtimeSettingsSave: "Save and apply",
  runtimeSettingsSaving: "Applying…",
  runtimeSettingsSaveFailed: "Failed to save runtime settings",
  setupDirty: "Uncommitted changes",
  setupClean: "Clean workspace",
  setupDetached: "Detached HEAD",
  setupNoCommits: "No commits yet",
  setupInvalidRepository: "Not a valid Git repository",
  historyScroll: "{0} shown · scroll down to load more",
  productName: "Workspace Workbench",
  changesTitle: "Workspace Changes",
  openWorkbench: "Open Workspace Workbench",
  headerLabel: "Workbench",
  text_fb36ad230f: "Observer request failed",
  text_f7e720248d: "Fast-forward candidate",
  text_ee5b0077ae: "Already contained",
  text_da56864458: "Diverged",
  text_27b5842c97: "Needs confirmation",
  text_c7ae08f54c: "Select a Workspace",
  text_4f91d2c9ad: "Read-only · current source",
  text_f496a15d9d: "Observation incomplete; retrying.",
  text_b30f770e31: "Observation incomplete; try again later.",
  text_b71f1b83e5: "The first observation is not complete; try again later.",
  text_bb57803d41: "The main workspace supports observation only; Agent handoff is unavailable",
  text_d7dd46e5e3: "Start the handoff from the coordinator Agent panel",
  text_afa9beb681: "Enter a goal for this handoff first",
  text_36cdf2a07a: "Continue the previous handoff: complete the read-only preflight; stop and report if it still differs.",
  text_a2eb60ef6c: "Execution Agent created",
  text_0561f1d18e: "Execution Agent is running",
  text_050246dd54: "Execution Agent restored",
  text_962c002fa2: "Handoff submitted",
  text_b4f57a0af8: "Handoff incomplete",
  text_341baadc12: "Handoff request failed",
  text_2fb0b81c28: "Merge brief copied",
  text_514f0cbbf2: "Copy failed; select and copy the text instead",
  text_1623afda9e: "New Workspace",
  text_76848596cb: "Workspace name",
  text_deb3990191: "Creation failed",
  text_1680b04bf6: "Creating…",
  text_fcbd093292: "Create",
  text_1b37d56f7a: "Handoff goal",
  text_99ad8551f2: "Handoff",
  text_ddb6624fda: "Observer unavailable",
  text_d019a92a84: "Refresh observation",
  text_0334dc4b93: "Data may be stale · ",
  text_a6625c543c: "Last observation · ",
  text_15c5640f77: "Waiting to start",
  text_fb0309dda4: "Initializing",
  text_1f425b6bf0: "Running",
  text_837e7a109a: "Idle",
  text_4c5958e011: "Waiting for permission",
  text_e99b48a29b: "Completed",
  text_059c4d4016: "Blocked",
  text_9746cfc7d2: "Execution failed",
  text_f628761bf5: "Closed",
  text_5cfbea2b76: "Archived",
  text_87f8d08d81: "Not handed off",
  text_b21b631cd5: "Reading",
  text_95abdc4ebd: "Status unknown",
  text_f7acefd2d4: "View",
  text_2b6021df2f: "Retry handoff",
  text_88b31c6b96: "Observer layout",
  text_07333899fd: "Adjust how the three observation areas are displayed",
  readOnlyObservation: "Read-only observation",
  toolchainLabel: "Toolchain · ",
  text_6cea90adcf: "Workspace Workbench",
  text_ca42ecd50e: "Observation · Agent status",
  text_1744b62533: "Open Workbench layout menu",
  text_5f6a1bf190: "Collapse all",
  text_66c98ab6d8: "Expand all",
  text_e003f209ca: "Restore default layout",
  text_4d0b4688c7: "Cancel",
  text_21eaf73725: "Refreshing",
  text_778fc8f994: "All",
  text_284b34e15f: "Needs attention",
  text_05162ec10a: "Unpushed",
  text_be78b20585: "History",
  text_80bf719ff7: "Observing…",
  text_205b4561ed: "Workspaces",
  text_daa32fe25c: "No matching workspaces.",
  text_96c3e67563: "Loading workspaces…",
  text_07f7471155: "No workspace data is available.",
  text_981b8eb33f: "Select a workspace to begin observing.",
  text_6bb9866496: "No readable repositories in this workspace.",
  text_9fd34d1b5f: "Needs preparation",
  text_5395180221: "Partially complete",
  text_273309c58d: "Preparation failed",
  text_005b60faae: "mise missing",
  text_81772f8606: "System command missing",
  text_a94df0c5c2: "Version conflict",
  text_9e44dbbc0e: "Prepare the runtime for this repository.",
  toolchainPrepare: "Prepare runtimes",
  toolchainPreparing: "Preparing runtimes…",
  text_f52ac96bcc: "MISE toolchain ·",
  text_ededcbb377: "repos",
  text_f9f75e6112: "Not updated",
  text_80a8716fca: "Full history",
  text_ddde5db955: "No upstream configured",
  text_62b4069970: "Return to current scope",
  text_a86af73bae: "Hide details",
  text_4f55ee1e68: "Details",
  text_1405df66cb: "base ",
  text_fcabadb2a7: "Loading…",
  text_a07cd6a10e: "No commits to show.",
  text_76c6f5f575: "Loading history…",
  text_f9d6d6a329: "History limit reached",
  text_5731f87e8f: "Reached the start of history",
  text_c9b020caa5: " · shown ",
  text_ef7c82a2b7: "WORKTREE",
  text_41e5243e2d: "Directory",
  text_49deaf7da2: "Files",
  text_95c0f75473: "Changed files refresh incomplete · keeping the last observation",
  text_5ee36e41d4: "No file changes in this scope.",
  text_5200400653: "Select workspace",
  text_91a9479226: "commits ·",
  text_9de8dab0bd: "Overlap ·",
  text_be8ffa22c8: "Merge brief",
  text_55f59bc2f0: "Copy all",
  text_5d5815647c: "Hide",
  text_b0e24833f7: "Show",
  text_5e509c6853: "Select a workspace to analyze.",
  text_a7fc5b37a4: "File changes are temporarily unavailable. Try again later.",
  text_c580606e1c: "Uncommitted",
  text_09cbc97ae2: "Commit",
  text_d1d2ccdd33: "Branch commits",
  text_eb8343b3df: "WORKSPACE / REVIEW WORKBENCH",
  text_01970ba582: "Workspace Changes",
  text_45300063e6: "Read-only file review · ",
  text_6298371965: "Select a changed file",
  switchToUnified: "Use unified review",
  switchToSplit: "Use split review",
  readOnlyBadge: "Read-only file review",
  text_9af2506454: "READ ONLY",
  text_336884b48e: "Select a file from Workspace Workbench to open it here.",
  text_e80b21bb56: " · head ",
  text_6d6e071a12: "Not updated · keeping the last Diff",
  text_a74b5d91fa: "Loading file changes…",
  text_982b60ebcc: "Select a file to begin review",
  text_5720774925: "Changed tree opens files in this main tab; the original Agent session remains available.",
  text_a1a0e61a02: "Binary file",
  text_8476fa5fe9: "This file has no readable text Diff.",
  text_fd707df26d: "No text changes to display",
  text_81f977c1ab: "The file may be empty, missing, or Git did not return a patch.",
  text_1d3d755616: "Diff content was truncated by the Observer limit.",
  text_dd4a011844: "+ added",
  text_e103af637d: "~ modified",
  text_2e359e4f5a: "− removed",
  text_0d310558b7: "Previous change hunk",
  text_d8b1574142: "Next change hunk",
  text_db427e2fe9: "Worktree missing",
  text_e0ea8945c4: "Invalid workspace record",
  text_ec1e4a1e10: "Invalid file path",
  text_8c9ee7d66a: "File is no longer in the current change scope",
  text_e7404b46f4: "Commit unavailable",
  text_f3ec0129e4: "Base commit missing",
  text_2f51f7e68d: "Repository is not part of this workspace",
  text_caa94a3fdf: "Repository is detached",
  text_6b9afea9f1: "Details required",
  text_6dbf7070d6: "Not observed",
  text_9e636642d6: "just now",
  text_adea7d427f: "observed just now",
  text_fcd9714424: "No activity",
  text_6478dde454: "Time unknown",
  text_3f2e139043: "Failed to read Paseo settings",
  text_c075ee72ab: "Invalid Paseo settings",
  text_abffafb4f9: "Workbench query timed out; the last observation was kept.",
  text_64c3cc39e8: "Workbench service is not running.",
  text_83008521f9: "Workbench service is temporarily unavailable.",
  text_61af484c81: "Observed {0} minutes ago",
  text_607909447d: "{0} minutes ago",
  text_87a6439b2e: "{0} hours ago",
  text_9094e27946: "{0} days ago",
  text_f41a05dfe8: "Agent handoff status: {0}",
  text_b5d0217a47: "Selected commit",
  text_b6a933155a: "Uncommitted changes",
  text_f30d1e7faf: "Branch changes",
  text_eac4c5d4a1: "Commit graph",
  text_22c7a14625: "Uncommitted {0}",
  text_46b798f402: "Branch changes {0}",
  text_f69ff23be4: "Load more commits · {0} shown",
  text_29e918bbdd: "  Uncommitted · {0}",
  text_2e046dd497: "{0} workspaces",
  text_c91e6e6a53: "Repositories",
  text_8fae4f2a02: "No changes",
  text_e50d9d028a: "Target branch",
  text_a5b4c3b08d: "Select target branch",
  text_39e5b16a6b: "Adjust {0} section height",
  diffOverview: "Diff overview",
  diffHunk: "Diff hunk {0}",
  reviewTargetBranch: "Target branch",
  agentCoordinatorRequired: "Start the handoff from the coordinator session",
  workspacePreviewRequired: "Run the read-only Workspace preview first; execute requires the same request identity.",
  agentModeUnconfirmed: "The execution mode or permissions could not be verified. Check the coordinator session and retry.",
  agentBusyOtherTask: "The Agent is handling another handoff task",
  agentClosedRecovery: "The existing Agent is closed. Recover it explicitly; no duplicate Agent was created.",
  createSearch: "Search repositories",
  createBase: "Set base (source HEAD by default)",
  createMissing: "Source unavailable",
  createCatalogFailed: "Repository catalog unavailable. Reopen and retry.",
  createResize: "Adjust Workspace creation dialog height",
  agentContextUnavailable: "The current session is not connected to Workbench tools. Create a coordinator session.",
  agentContextLoading: "Checking Workbench tool status…",
  agentContextReady: "Workbench tools connected",
  workspaceStatusDirty: "dirty",
  workspaceStatusUnpushed: "unpushed",
  workspaceStatusNeedsReview: "needs review",
  workspaceStateRemoved: "removed",
  workspaceStateDeletionPending: "pending deletion",
  workspaceStateCreateFailed: "creation failed",
  workspaceCreateFailedTitle: "Workspace creation failed",
  workspaceCreateFailedDescription: "Creation did not finish, so there is no observable Git worktree or commit graph.",
  workspaceCreateFailedRecovery: "Prepare the toolchain first, or remove this failed record and create the Workspace again.",
  workspaceDelete: "Remove Workspace",
  workspaceRestore: "Restore Workspace",
  workspacePermanentDelete: "Permanently delete",
  workspaceDeleteImpact: "Review deletion impact",
  workspaceDeleteTitle: "Delete Workspace",
  workspaceDeleteDescription: "A normal removal only hides the Workspace and keeps branches, commits, uncommitted changes, and task records.",
  workspaceDeleteRunningTask: "Running tasks",
  workspaceDeleteDirty: "Uncommitted changes",
  workspaceDeleteUnpushed: "Unpushed commits",
  workspaceDeleteExternal: "External references",
  workspaceDeletePreserve: "Preserves",
  workspaceDeleteLose: "Permanent deletion removes",
  workspaceDeleteConfirm: "Confirm permanent deletion",
  workspaceDeleteCancel: "Cancel",
  workspaceDeleteQueued: "A task is running. The Workspace is pending deletion and new tasks are blocked.",
  workspaceDeleteReady: "The task has finished; you can complete the removal.",
  workspaceDeleteSuccess: "Workspace removed. You can restore it from History.",
  workspaceRestoreSuccess: "Workspace restored.",
  workspacePermanentDeleteSuccess: "Workspace permanently deleted; branches and external references were preserved.",
  workspaceDeleteFailed: "Workspace deletion failed",
  workspaceDeleteStopTask: "Stop or finish the running task first",
  workspaceDeleteTaskStillRunning: "A task is still running; permanent deletion is unavailable",
  workspaceDeletePermanentWarning: "This cannot be undone. Managed worktrees and uncommitted files will be removed; branches are not deleted.",
  workspaceDeleteRuntimeState: "Runtime records",
  workspaceDeleteRuntimeImpact: "Permanent deletion clears this Workspace's Agent binding and Review records, but does not delete the external Agent itself.",
  workspaceDeleteRuntimeBinding: "Agent binding",
  workspaceDeleteRuntimeReview: "{0} Review record(s)",
  workspaceDeleteUnavailable: "Deletion impact is unavailable. Refresh and try again.",
  workspaceDeleteBranchPreserved: "Branches, commits, and external references are not deleted by logical removal.",
  tabWorkspace: "Workspace",
  tabReviewSet: "Review set",
  tabAgentReview: "Agent Review",
  reviewTitle: "Agent Review",
  reviewNoFlow: "This workspace has no review flow yet.",
  reviewLoading: "Loading review flow…",
  reviewStatusWaitingExecution: "Waiting for execution",
  reviewResumeWaitingReport: "Review flow restored; waiting for a new completion report from the execution session. No task is resent. You can also start review after execution finishes.",
  reviewStatusReady: "Ready for review",
  reviewStatusQueued: "Queued",
  reviewStatusReviewing: "Reviewing",
  reviewStatusChanges: "Changes requested",
  reviewStatusFixing: "Fixing",
  reviewStatusApproved: "Approved",
  reviewStatusBlocked: "Blocked",
  reviewStatusFailed: "Failed",
  reviewStatusStopping: "Stopping",
  reviewStatusStopped: "Stopped",
  reviewStatusLimit: "Round limit reached",
  reviewRound: "Round {0} / {1}",
  reviewRoundShort: "Round {0}",
  reviewHistory: "History: {0}",
  reviewExecutionAgent: "Execution Agent",
  reviewReviewer: "Reviewer",
  reviewRepair: "Execution Agent repair",
  reviewEventStarted: "Review flow started",
  reviewEventExecutionTurnEnded: "Execution turn ended",
  reviewEventReady: "Execution Agent submitted the work for review",
  reviewEventQueued: "Review queued",
  reviewEventReviewerCreated: "Read-only Reviewer created",
  reviewEventReviewStarted: "Review started",
  reviewEventCandidate: "Candidate review result received",
  reviewEventResult: "Review result",
  reviewEventRepairRequested: "Repair requested from the execution Agent",
  reviewEventRepairSent: "Repair task sent",
  reviewEventPaused: "Review paused",
  reviewEventResumed: "Review resumed",
  reviewEventStopped: "Review stopped",
  reviewEventFailed: "Review failed",
  reviewEventBlocked: "Review blocked",
  reviewEventExpired: "Reviewed version expired",
  reviewEventFinished: "Review flow finished",
  reviewRoleExecution: "Execution Agent",
  reviewRoleReviewer: "Reviewer",
  reviewRoleRepair: "Execution Agent repair",
  reviewCompleted: "Completed",
  reviewExpand: "Expand full content",
  reviewCollapse: "Collapse full content",
  reviewLatestResult: "Latest review result",
  reviewFindingCount: "{0} findings",
  reviewNoFindings: "No required fixes",
  reviewCheckPassed: "Passed",
  reviewCheckFailed: "Failed",
  reviewCheckNotRun: "Not run",
  reviewCheckUnavailable: "Unavailable",
  reviewSeverityInfo: "Suggestion",
  reviewSeverityWarning: "Warning",
  reviewSeverityError: "Error",
  reviewViewDiff: "View diff",
  reviewViewExecution: "Open execution session",
  reviewViewReviewer: "Open review session",
  reviewViewConversation: "View full conversation",
  reviewChanges: "Changes",
  reviewTests: "Tests",
  reviewKnownLimitations: "Known limitations",
  reviewStart: "Start review",
  reviewContinue: "Continue review",
  reviewRepairAction: "Continue repair",
  reviewStop: "Stop",
  reviewResume: "Resume flow",
  reviewStartNew: "Start new review",
  reviewSettingsMenu: "Review settings",
  reviewSettingsTitle: "Review settings",
  agentSessionSettings: "Agent session settings",
  reviewSettingsScopeProject: "This project",
  reviewSettingsScopeGlobal: "Global defaults",
  reviewSettingsInheritedHint: "Fields without a project override inherit global defaults.",
  agentSessionPermissionSettings: "New execution Agent permissions",
  agentSessionPermissionHint: "Only affects execution Agents created from now on; existing Agents are unchanged.",
  agentSessionPermissionInherit: "Follow current Agent",
  agentSessionPermissionAuto: "Auto",
  agentSessionPermissionAutoReview: "Auto review",
  agentSessionPermissionFullAccess: "Full access",
  reviewSettingsIndependent: "Independent session",
  reviewSettingsIndependentShort: "Independent",
  reviewSettingsChildAgent: "Child Agent",
  reviewSettingsFollowDefault: "Follow default",
  reviewSettingsProviderOverrides: "Provider overrides",
  reviewSettingsMode: "Review mode",
  reviewSettingsModeOff: "Off",
  reviewSettingsModeManual: "Manual",
  reviewSettingsModeAutomatic: "Automatic",
  reviewSettingsAutoFix: "Automatic repair",
  reviewSettingsManualFix: "Manual repair",
  reviewSettingsRole: "Reviewer role",
  reviewSettingsInstructions: "Review instructions",
  reviewSettingsMaxRounds: "Maximum review rounds",
  reviewSettingsTimeout: "Timeout",
  reviewSettingsReviewerTimeout: "Review",
  reviewSettingsRepairTimeout: "Repair",
  reviewSettingsReviewerTimeoutPlaceholder: "Review min",
  reviewSettingsRepairTimeoutPlaceholder: "Repair min",
  reviewSettingsChecks: "Checks",
  reviewSettingsReviewerSession: "Reviewer session",
  reviewCoordinator: "Coordinator review",
  handoffMaterials: "Handoff materials",
  handoffMaterialsUnavailable: "Handoff materials are unavailable",
  handoffConversation: "Conversation archive",
  handoffRequired: "Required sources",
  handoffFetched: "Fetched (not proof of understanding)",
  handoffNextPage: "Next segment",
  reviewCoordinatorWaiting: "Waiting for coordinator to be idle",
  reviewCoordinatorUncertain: "Review delivery unconfirmed",
  reviewCoordinatorSent: "Waiting for coordinator acceptance",
  reviewIndependentSwitch: "Use independent Reviewer",
  reviewCoordinatorOpen: "Open coordinator conversation",
  reviewSettingsReuse: "Reuse session",
  reviewSettingsNewPerRound: "New each round",
  reviewSettingsExecutionModel: "Execution model",
  reviewSettingsReviewerModel: "Reviewer model",
  reviewSettingsFollowExecution: "Follow execution session",
  reviewSettingsResetExecution: "Reset execution model inheritance",
  reviewSettingsResetReviewer: "Reset Reviewer model inheritance",
  reviewSettingsResetAll: "Reset all project inheritance",
  reviewSettingsSave: "Save settings",
  reviewSettingsSaved: "Review settings saved",
  reviewSettingsSaveFailed: "Failed to save review settings",
  reviewSourceProject: "Project",
  reviewSourceGlobal: "Global",
  reviewSourceDefault: "Default/follow",
  reviewSourceDefaultShort: "Default",
  reviewDefaultRole: "Code reviewer",
  reviewDefaultInstructions: "Check requirement fit, correctness, regressions and tests; keep the implementation simple.",
  reviewPromptIntro: "Review session {0}, round {1}.",
  reviewPromptRead: "The server authenticates read and result calls. Read the fixed snapshot before deciding.",
  reviewPromptIdentity: "Expected snapshot identity: {0}; expected diff identity: {1}.",
  reviewPromptOriginal: "Original task context: {0}.",
  reviewPromptPrevious: "Previous review result and repair evidence: {0}.",
  reviewPromptReturn: "Return stable finding IDs; mark approved only when no required fix remains.",
  reviewPromptLanguage: "Return the review summary, findings, suggestions, and checks in English.",
  reviewSystemRole: "You are the {0}.",
  reviewSystemReadOnly: "You are strictly read-only. Use the dedicated review tools to read the fixed snapshot and submit a structured result.",
  reviewSystemNeverWrite: "Do not edit business files, run mutating commands, delegate, create another Agent, or merge.",
  handoffPacket: "Handoff materials",
  handoffPreview: "Preview handoff",
  handoffPreviewTitle: "Confirm Agent handoff",
  handoffPreviewHint: "After confirmation, these requirements will be frozen and provided to both the execution Agent and Reviewer.",
  handoffConfirm: "Confirm handoff",
  handoffEdit: "Edit materials",
  handoffDone: "Done editing",
  handoffUnderstanding: "Requirement understanding",
  handoffUnderstandingPlaceholder: "Explain in your own words what problem is being solved, for whom, and what success looks like.",
  handoffPlan: "Plan (one item per line)",
  handoffPlanPlaceholder: "Example: update settings page; add empty state; add tests.",
  handoffAcceptance: "Acceptance criteria (one item per line)",
  handoffAcceptancePlaceholder: "Example: show empty state when unconfigured; show success after save.",
  handoffReferences: "Reference files/images (one per line)",
  handoffReferencesPlaceholder: "Use repo:path; use asset:ID for an image registered by the coordinator.",
  handoffAvailableAssets: "Available image assets (click to add)",
  handoffReviewInstructions: "Task-specific review instructions",
  handoffReviewInstructionsPlaceholder: "Example: compare layout, states, and interactions against the draft image.",
  handoffPacketHint: "These materials are frozen with this task and provided to the execution Agent and Reviewer.",
  handoffNoPacket: "No additional handoff materials provided.",
  handoffReferenceCount: "{0} reference materials",
  handoffAcceptanceCount: "{0} acceptance criteria",
  reviewErrorGeneric: "The review flow is temporarily unavailable",
  reviewErrorExecutionRequired: "Complete the execution Agent task and submit its review report first.",
  reviewErrorExecutionBusy: "The execution Agent is still running. Start the review after it finishes.",
  reviewErrorModelUnavailable: "The configured Reviewer model is unavailable.",
  reviewErrorReviewerUnavailable: "The Reviewer session could not start.",
  reviewErrorSnapshotStale: "The code changed during review. Start a new review.",
  reviewErrorReadonlyUnavailable: "The environment could not confirm the Reviewer's read-only permissions.",
  reviewErrorDisabled: "Review is disabled.",
  reviewErrorExecutionRequiredShort: "Complete the execution Agent task first.",
  reviewErrorExecutionUnavailable: "The execution Agent is unavailable.",
  reviewErrorExecutionIdentity: "The execution Agent does not match this workspace.",
  reviewErrorReviewNotReady: "There is no execution result ready for review.",
  reviewErrorSessionNotFound: "The review flow could not be found.",
  reviewErrorStateConflict: "The review state changed. Refresh and try again.",
  reviewErrorReviewNotActive: "The review flow has ended and cannot accept this action.",
  reviewErrorReviewerBusy: "The Reviewer is still handling the previous round.",
  reviewErrorReviewerTimeout: "The Reviewer timed out.",
  reviewErrorReviewerInvalidResult: "The Reviewer returned an invalid result format.",
  reviewErrorCancelUnavailable: "The environment could not confirm that the stop completed.",
  reviewErrorPermission: "The Reviewer is waiting for permission.",
  reviewErrorCodeLabel: "Error code",
  reviewFindingNeedsFix: "Needs fix",
  reviewFindingSuggestion: "Suggestion",
  reviewUnreviewed: "Unreviewed",
  reviewCheckEvidence: "Evidence",
  graphCommitChanges: "Commit changes",
  graphHeadWorktree: "HEAD → worktree",
  graphBaseHead: "Base → HEAD",
  graphBaseLabel: "base",
  commitDetails: "Commit details",
  commitAuthor: "Author",
  commitTime: "Committed",
  commitReferences: "Branches/tags",
  commitParentCount: "{0} parent(s)",
  commitMerge: "Merge commit",
  commitBase: "Base commit",
  commitTimeUnknown: "Time unavailable",
  commitAuthorUnknown: "Unknown author",
  commitNoReferences: "No branch or tag",
  graphDetached: "No upstream",
  branchMissing: "Worktree missing",
  branchDetached: "Detached HEAD",
  fileCountLabel: "{0} file(s)",
  repoCountLabel: "{0} repo(s)",
  gitLabel: "Git",
  localStorageLabel: "Local · {0}",
  externalStorageLabel: "External · {0}",
  languageFollowSystem: "Follow Paseo/system",
  languageChinese: "Chinese",
  languageEnglish: "English",
};

export const copy: WorkbenchCopy = zhCopy;

function localeCandidate(value: unknown): string | null {
  if (typeof value === "string") return value;
  if (!value || typeof value !== "object") return null;
  const record = value as Record<string, unknown>;
  for (const key of ["locale", "language", "languageTag"]) {
    if (typeof record[key] === "string") return record[key] as string;
  }
  return null;
}

export function normalizeWorkbenchLocale(value: unknown): WorkbenchLocale | null {
  const candidate = localeCandidate(value)?.toLowerCase();
  if (!candidate) return null;
  return candidate === "zh" || candidate.startsWith("zh-") ? "zh-CN" : "en-US";
}

export function resolveWorkbenchLocale(input?: unknown): WorkbenchLocale {
  const explicit = normalizeWorkbenchLocale(input);
  if (explicit) return explicit;
  const runtime = globalThis as unknown as { navigator?: { language?: string }; Intl?: typeof Intl };
  const browser = normalizeWorkbenchLocale(runtime.navigator?.language);
  if (browser) return browser;
  try {
    const system = normalizeWorkbenchLocale(Intl.DateTimeFormat().resolvedOptions().locale);
    if (system) return system;
  } catch {
    // Hosts without Intl use the compatibility default below.
  }
  return "zh-CN";
}

export function getWorkbenchCopy(locale: WorkbenchLocale = "zh-CN"): WorkbenchCopy {
  return locale === "en-US" ? enCopy : zhCopy;
}

export function formatCopyFrom(source: WorkbenchCopy, key: keyof WorkbenchCopy, values: unknown[]): string {
  return source[key].replace(/\{(\d+)\}/g, (_, index) => String(values[Number(index)] ?? ""));
}

export function formatCopy(key: keyof WorkbenchCopy, values: unknown[]): string {
  return formatCopyFrom(copy, key, values);
}

const reviewErrorKeys: Record<string, keyof WorkbenchCopy> = {
  review_disabled: "reviewErrorDisabled",
  execution_agent_required: "reviewErrorExecutionRequiredShort",
  execution_agent_unavailable: "reviewErrorExecutionUnavailable",
  execution_agent_busy: "reviewErrorExecutionBusy",
  execution_agent_identity_changed: "reviewErrorExecutionIdentity",
  execution_turn_failed: "reviewErrorExecutionUnavailable",
  execution_needs_input: "reviewErrorExecutionRequiredShort",
  review_not_ready: "reviewErrorReviewNotReady",
  review_session_not_found: "reviewErrorSessionNotFound",
  review_state_conflict: "reviewErrorStateConflict",
  review_not_active: "reviewErrorReviewNotActive",
  reviewer_model_unavailable: "reviewErrorModelUnavailable",
  reviewer_busy: "reviewErrorReviewerBusy",
  reviewer_timeout: "reviewErrorReviewerTimeout",
  reviewer_invalid_result: "reviewErrorReviewerInvalidResult",
  reviewer_permission_required: "reviewErrorPermission",
  cancel_unavailable: "reviewErrorCancelUnavailable",
  review_snapshot_stale: "reviewErrorSnapshotStale",
  review_snapshot_unavailable: "reviewErrorGeneric",
  reviewer_bridge_unavailable: "reviewErrorReviewerUnavailable",
  reviewer_bridge_endpoint_unavailable: "reviewErrorReviewerUnavailable",
  reviewer_identity_changed: "reviewErrorReviewerUnavailable",
};

export function localizedReviewError(error: { code?: unknown } | null | undefined, source: WorkbenchCopy, fallback?: string): string {
  const code = typeof error?.code === "string" ? error.code.split(":", 1)[0] : "";
  return reviewErrorKeys[code] ? source[reviewErrorKeys[code]] : fallback || source.reviewErrorGeneric;
}
